CREATE OR REPLACE PROCEDURE PRO_SYS_WORKCPITEM_TOCHARGEDE_GET
(
I_I_ID IN NUMBER, --i_id
V_V_INFO OUT VARCHAR2, --成功执行信息为：‘success’，失败执行信息为错误信息
V_C_CURSOR OUT SYS_REFCURSOR --成功返回结果集
) IS
BEGIN
BEGIN
OPEN V_C_CURSOR FOR
SELECT T.* FROM SYS_WORKCPITEM_TOCHARGEDE T
WHERE T.I_ID = I_I_ID;
V_V_INFO := 'success';
EXCEPTION
WHEN OTHERS THEN
V_V_INFO := sqlerrm;
END;
END PRO_SYS_WORKCPITEM_TOCHARGEDE_GET;